# Site Configuration

# Theme
theme: default

# HTML Language setting
lang: "en"

# Google Analytics tracking id (leave blank if not using)
google_analytics_id:

# HTML Title
title: "Dogame's Links"

# Avatar image path
avatar: "art/image0.jpeg"

# Name section text
name: "@Dogame"

# Tagline section text
tagline: >-
  Artist & Host of Drawn to the Mic

# List of links
links:
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://www.instagram.com/Dogame__"
      alt: "Dogame's Instagram"
      title: "Dogame's Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "Twitter"
      url: "https://twitter.com/Dogame_"
      alt: "Dogame's Twitter"
      title: "Dogame's Twitter"
      target: "_blank"
  - link:
      icon: "fa-solid fa-paintbrush"
      text: "Drip Haus"
      url: "https://drip.haus/dogame"
      alt: "Dogame's Drip Haus"
      title: "Dogame's Drip Haus"
      target: "_blank"

# Socials (optional — these show as icons, usually in the footer/header)
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/Dogame__"
      title: "Instagram"
      alt: "Dogame's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/Dogame_"
      title: "Twitter"
      alt: "Dogame's Twitter"
      target: "_blank"
  - social:
      icon: "fa-solid fa-paintbrush"
      url: "https://drip.haus/dogame"
      title: "Drip Haus"
      alt: "Dogame's Drip Haus"
      target: "_blank"

# Footer text
footer: >
  Thanks for stopping by!

# Footer copyright message
copyright: >
  © 2025 Dogame. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
